### ISSUE TITLE
调用接口的时候全部报错

### ISSUE THREAD

**Issue by qiu1518977696** [dairoot/school-api#1]
/xsgrxx.aspx?gnmkdm=N121501&xh=51630104
{'error': school_code:None, Error msage: 用户信息接口，获取用户信息失败}
/xskbcx.aspx?gnmkdm=N121603&xh=51630104
<Response [302]>
{'error': school_code:None, Error msage: 课表接口，课表接口已关闭}
f12看我们学习的接口发现还有一个xm字段，然后增加后还是报错，
希望大佬看见能联系我下QQ192907881万分感谢

**Comment by dairoot** [comment]
兼容问题
