### ISSUE TITLE
使用redis 多账号 查成绩时概率性302问题

### ISSUE THREAD

**Issue by zsjyjishukong** [dairoot/school-api#11]
当使用redis时，使用一台服务器对多个（测试时两个）账号进行查成绩操作，第一次查询没问题，当使用redis里的cookie再次请求时问题较少，但是第三次请求时，会有较大概率某一个账号的xscjcx.aspx会出现302，较小概率两个同时302，较小概率两个同时正确，请问您觉得问题大概在哪里

**Comment by dairoot** [comment]
提供一下教务系统地址

**Comment by zsjyjishukong** [comment]
http://jws.hebiace.edu.cn

**Comment by dairoot** [comment]
无法打开该地址，留一下QQ。

**Comment by zsjyjishukong** [comment]
好的  
`1361882279`

**Comment by zsjyjishukong** [comment]
您好，还未收到您的好友请求
