### ISSUE TITLE
查询课表出错

### ISSUE THREAD

**Issue by u4250** [dairoot/school-api#12]
代码和线上测试接口都查不了
如图
![image](https://user-images.githubusercontent.com/48275726/78634365-602b3400-78d6-11ea-895a-9b204a8b3a79.png)

**Comment by dairoot** [comment]
提供一下教务系统地址

**Comment by u4250** [comment]
http://jwcwebs.kmu.edu.cn/

**Comment by u4250** [comment]
> 提供一下教务系统地址

http://jwcwebs.kmu.edu.cn/

**Comment by dairoot** [comment]
课表解析问题，不打算兼容
