### ISSUE TITLE
get_score 成绩信息可以查询到，但是查询不全

### ISSUE THREAD

**Issue by handsomeWeiye** [dairoot/school-api#15]
我校的地址 http://202.115.80.211/default2.aspx#a
我校的成绩接口 http://202.115.80.211/xscjcx.aspx?xh=201711533704&xm=%B6%C5%CE%B0%D2%B5&gnmkdm=N121605
选择的 接口 use_api=3

出现的问题，只有公选课的成绩被查询到，专业课的成绩一律没有
解析出的table中就没有专业课的信息（专业课信息的标签为<tr class='alt'>）

希望楼主大大能够帮忙解决一下这个问题，拜托啦

我猜测可能是请求连接的参数有问题

**Comment by handsomeWeiye** [comment]
问题已经解决：成绩查询提交的参数有问题，更换后问题解决
![image](https://user-images.githubusercontent.com/43540406/79441354-b2bccc80-8009-11ea-94a2-e0bcca3d7a14.png)

**Comment by handsomeWeiye** [comment]
我校的成绩查询提交参数为
        payload = {
            '__VIEWSTATE': view_state,
            
            'btn_zcj': '历年成绩',
            'ddl_kcxz':'',
            'hidLanguage':'',
            
            'ddlXN': '',
            'ddlXQ': ''
        }

**Comment by dairoot** [comment]
hidLanguage 传空吗？
