### ISSUE TITLE
【求助】{'error': '验证码获取失败'}

### ISSUE THREAD

**Issue by 26324636** [dairoot/school-api#17]
请问为什么登录一直是{'error': '验证码获取失败'}啊，学校的验证码地址也是/CheckCode.aspx

**Comment by dairoot** [comment]
发一下教务系统地址

**Comment by 26324636** [comment]
http://jw2.ypc.edu.cn 方便留个联系方式不，我提供账号密码供测试哈------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;dai&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月27日(星期二) 晚上8:26
收件人:&nbsp;&quot;dairoot/school-api&quot;<school-api@noreply.github.com&gt;;
抄送:&nbsp;&quot;Effort&quot;<26324636@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dairoot/school-api] 【求助】{&#39;error&#39;: &#39;验证码获取失败&#39;} (#17)

**Comment by 26324636** [comment]
账号:0701170113 密码:123123as 直接发邮箱叭，麻烦大佬啦------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;dai&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月27日(星期二) 晚上8:26
收件人:&nbsp;&quot;dairoot/school-api&quot;<school-api@noreply.github.com&gt;;
抄送:&nbsp;&quot;Effort&quot;<26324636@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dairoot/school-api] 【求助】{&#39;error&#39;: &#39;验证码获取失败&#39;} (#17)

**Comment by dairoot** [comment]
暂不支持该教务系统版本

**Comment by 26324636** [comment]
那请问是不是得使用fznew新版的呀


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dairoot/school-api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月27日(星期二) 晚上10:17
收件人:&nbsp;"dairoot/school-api"<school-api@noreply.github.com&gt;;
抄送:&nbsp;"Effort🐬"<26324636@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dairoot/school-api] 【求助】{'error': '验证码获取失败'} (#17)





 
暂不支持该教务系统版本

**Comment by dairoot** [comment]
fznew 什么意思？

**Comment by 26324636** [comment]
https://github.com/NeroAsmarr/zfnew
zfnew，新版正方教务教务系统API




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dairoot/school-api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 下午5:34
收件人:&nbsp;"dairoot/school-api"<school-api@noreply.github.com&gt;;
抄送:&nbsp;"Effort🐬"<26324636@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dairoot/school-api] 【求助】{'error': '验证码获取失败'} (#17)





 
fznew 什么意思？
