### ISSUE TITLE
{'error': '获取view_state失败'}

### ISSUE THREAD

**Issue by maicent** [dairoot/school-api#18]
{'error': '获取view_state失败'}是我有什么地方没有设置对吗
`from school_api import SchoolClient
school = SchoolClient(url=隐藏下.edu.cn')
student = school.user_login('用户名','密码',timeout=10)

info_data = student.get_info()
print(info_data)`

**Comment by dairoot** [comment]
提供一下教务系统地址

**Comment by maicent** [comment]
> 提供一下教务系统地址

jwxt.hbnu.edu.cn

**Comment by dairoot** [comment]
该版本的教务系统不支持

**Comment by Farmer-chong** [comment]
该版本可以试一下这个repo: https://github.com/Farmer-chong/new-school-sdk

**Comment by FarmerChillax** [comment]
> > 提供一下教务系统地址
> 
> jwxt.hbnu.edu.cn

该版本可以试一下这个repo: https://github.com/Farmer-chong/new-school-sdk
