### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by SodiumAzide** [dairoot/school-api#3]
https://github.com/dairoot/school-api/blob/aaec718d08c2fab6d0071afd3753fb094998eb5f/setup.py#L7
`Collecting School-Api
  Downloading http://pypi.doubanio.com/packages/02/34/1e35ed122c9706b0c4f174e9b5bfa7d3fc00ca14c4eafde0d5e23cf4801b/School-Api-1.3.6.tar.gz (152kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\****\AppData\Local\Temp\pycharm-packaging\School-Api\setup.py", line 8, in <module>
        long_description = f.read().split("## User permissions")[0]
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x82 in position 25: illegal multibyte sequence`
加个encoding="utf8"????

**Comment by qwertyuiop6** [comment]
同

**Comment by SodiumAzide** [comment]
> 同

下载源码，加个encoding=”utf8“， 然后源码pip安装就行

**Comment by dairoot** [comment]
python2版本？ @SodiumAzide @qwertyuiop6

**Comment by dairoot** [comment]
已修复
