### ISSUE TITLE
接口bug 成绩以及课表无法获取

### ISSUE THREAD

**Issue by zsjyjishukong** [dairoot/school-api#5]
课表接口：error_message:课表接口，课表接口已关闭
成绩接口同样
经查，教务系统正常
查找到问题所在，在 client/api/score.py 67行 tag = "Datagrid1" if self.use_api != 3 else "DataGrid1"，删除if后的代码就可以查到
课表接口相同

**Comment by dairoot** [comment]
可否提供下教务系统地址？

**Comment by zsjyjishukong** [comment]
http://jws.hebiace.edu.cn/default2.aspx 对应的教务系统成绩的table id名是DataGrid1
课表现在依然在报错，我正在排查问题

**Comment by dairoot** [comment]
课表接口：error_message:课表接口，课表接口已关闭 ？ 那是否已确定教务系统真的可以查课表？

**Comment by zsjyjishukong** [comment]
确定可用

**Comment by zsjyjishukong** [comment]
抱歉，找到问题所在了，因为get_schedule忘记传参schedule_type了，但是score.py的问题希望修复

**Comment by dairoot** [comment]
已修复
