### ISSUE TITLE
多次请求flask失败

### ISSUE THREAD

**Issue by zsjyjishukong** [dairoot/school-api#7]
1. 在使用您提供的flask代码，测试使用成绩查询功能时，设置了一百次查询，无论设置sleep与否，都会较大概率返回500，最频繁的一次500的概率达到了0.68， 反回500时，score方法返回值为{'error': school_code:None, Error message: 成绩接口，可能是成绩接口地址不对，请尝试更改use_api值}
2. 在单独对get_score方法进行测试时，同样100次循环，可用率都达到了100%，没有出现报错的情况

**请问这种情况应该如何处理，究竟是哪里出现问题呢？**

**Comment by dairoot** [comment]
说的很明显了：“成绩接口，可能是成绩接口地址不对，请尝试更改use_api值”。

**Comment by zsjyjishukong** [comment]
您可能没有看懂我说的问题，是在循环请求中发生的问题，前面还在200，后面突然就会报500，期间没有更改过代码

**Comment by zsjyjishukong** [comment]
代码如下
```python
for i in range(0, 100):
    text = '第' + str(i) + '次测试，本次测试时间为' + time.strftime('%Y-%m-%d %H:%M:%S') + ',测试结果为：'
     url = 'http://localhost:5000/get_score?account=201xxxxxx&passwd=13xxxxxx'
    res = requests.get(url)
    text = text + str(res.status_code) + '\n'
```

**Comment by zsjyjishukong** [comment]
print的结果如下
>第0次测试，本次测试时间为2019-08-08 16:30:24,测试结果为：200
>……
>第7次测试，本次测试时间为2019-08-08 16:30:56,测试结果为：500
>第8次测试，本次测试时间为2019-08-08 16:30:57,测试结果为：500

**Comment by dairoot** [comment]
可能贵校教务系统网站的问题
1. 请求flask，是会调用user_login，进行重新登录，可能就在重复登录，造成了500问题
2. 你单独get_score循环，应该没有对user_login重复调用吧。
所以造成上述的差异

**Comment by zsjyjishukong** [comment]
好的，非常感谢您的回复，我们对这个问题着手进行测试，谢谢
