### ISSUE TITLE
还有一个问题

### ISSUE THREAD

**Issue by ATUFO** [dairoot/school-api#9]
你这里虽然处理了
```
<br/><br/>
```
但是，解析的结果不对

**Comment by ATUFO** [comment]
![image](https://user-images.githubusercontent.com/18240599/74309149-ff372200-4da4-11ea-92ac-3c4b81ad4c34.png)

**Comment by dairoot** [comment]
课表解析，已不打算兼容其他院校

**Comment by ATUFO** [comment]
好吧，不过真的好用。不好意思，我刚刚看到，功能是没错的。
